#!/bin/bash

echo ""
echo "======================="
echo "Accelerated Modeling Quick-Start"
echo "======================="
echo ""
echo "We really put a lot of effort in making this development as fast"
echo "as possible. To get started, simply copy and paste this command"
echo "to clone our basic example into your working directory:"
echo ""
echo "1) this installs an example module that inherits this modeling,"
echo "quickly allowing you to build your resource. Copy-and-paste into"
echo "terminal while in your node project directory:"
echo "cd node_modules/accelerated.api.model && npm run-script example ./../../ && cd ../../"
echo ""
echo "Once you've got some code to work with, make sure you install"
echo "either postgres or rethinkdb database drivers and their"
echo "provisioning scripts. Otherwise, your application won't work:"
echo ""
echo "a) postgres (pg)"
echo "cd node_modules/accelerated.api.model && npm run-script pg ./../../ && cd ../../"
echo ""
echo "b) rethinkdb (reql)"
echo "cd node_modules/accelerated.api.model && npm run-script reql ./../../ && cd ../../"
echo ""
echo "======================="
echo "Table Schema Creation"
echo "======================="
echo ""
echo "You'll notice two JSON files. These JSON files are mentioned"
echo "by ```index.js``` and define your resource's model schema."
echo "Modify these for Accelerated to appropriately manage your new"
echo "resource."
echo ""
echo "When you modify those JSON files, and you do not have your"
echo "tables (and/or columns) defined in your database, simply pass"
echo "```setup``` when running your application. Accelerated will"
echo "read the flag and then conditionally create the tables, so"
echo "that your resources have the appropriate db resources needed."
echo ""
echo "1) modify model-{'pg' or 'reql'}.json"
echo "2) run your application with 'node index.js setup'"
echo ""